I added html, css, linters config files
Hamas2000/Personal-Portfolio pull request #1
Opened 2024-06-01 08:37 UTC by Hamas2000

..

2024-06-04 10:06 UTC, ahzamir requested changes
@Hamas2000 

Hey hamasa, you have done a great job by adding this amazing design to your portfolio but still, your project has some issues to work on check the inline comments below:

2024-06-04 10:06 UTC, ahzamir commented on index.html
- Your code is not clean.

2024-06-04 10:06 UTC, ahzamir commented on index.html
> +		<button class="lets-talk" type="button">Let's talk</button>
- These two buttons do not have any functionality, remove them or add functionality to them
![Screenshot 2024-06-04 115509](https://github.com/Hamas2000/Personal-Portfolio/assets/96838030/bc90698f-98a3-43ef-876a-117957846601)

2024-06-04 10:06 UTC, ahzamir commented on styles.css
> +}
- You added only a few codes for your responsiveness, so your webpage does not look good in smaller versions.

![Screenshot 2024-06-04 115610](https://github.com/Hamas2000/Personal-Portfolio/assets/96838030/0b73dc84-53ed-4fd7-a661-25dc734b36ce)
![Screenshot 2024-06-04 115559](https://github.com/Hamas2000/Personal-Portfolio/assets/96838030/06a762cf-833c-4417-bcd9-0c4ec6c3844d)

![Screenshot 2024-06-04 115542](https://github.com/Hamas2000/Personal-Portfolio/assets/96838030/a949a803-de15-4672-a5b7-62c3890ec457)

2024-06-04 10:06 UTC, ahzamir commented on styles.css
> +}
- Try to change the sizings and design of your project in different screen sizes.

2024-06-06 08:55 UTC, Hamas2000 commented
@ahzamir thank you for your comment. 
would you please have a look on my project now?

2024-06-06 11:08 UTC, ahzamir commented
@Hamas2000 

- Please ask your partner for feedback.

- Although I can not see your partner's feedback on your repo still I will share my feedback with you next time you need to get your partner's feedback on your project then ask me for feedback, or if you mentioned your partner and she did not respond for 24 hours then you can ask me for feedback.

2024-06-06 11:16 UTC, ahzamir requested changes
Great job @Hamas2000  you have made a great designed portfolio, but still your webpage is not responsive and have some issues to work on:

- Check the comments below for more details

2024-06-06 11:16 UTC, ahzamir commented on styles.css
![Screenshot 2024-06-06 130448](https://github.com/Hamas2000/Personal-Portfolio/assets/96838030/5320e389-0090-4e28-b852-15e7563c9ebc)
![Screenshot 2024-06-06 130436](https://github.com/Hamas2000/Personal-Portfolio/assets/96838030/bf1ba0cf-eb33-4f2f-9b1e-cb35370ad721)
![Screenshot 2024-06-06 130422](https://git
![Screenshot 2024-06-06 130406](https://github.com/Hamas2000/Personal-Portfolio/assets/96838030/aa28a351-982c-4433-9081-6649163f30c8)
hub.com/Hamas2000/Personal-Portfolio/assets/96838030/e64d1e33-3731-4018-9890-80d92a836737)

- Although your design looks great on the Desktop version, your webpage is not responsive for the mobile version, and as you can see it's not looking great.
  - HINT: Don't use fixed widths for your divs, containers, or images like 500px or 400px in the desktop version as it will affect your mobile version and if you used it then you have to change the size to smaller in your mobile version.

2024-06-06 11:16 UTC, ahzamir commented on index.html
> +  </section>
![image](https://github.com/Hamas2000/Personal-Portfolio/assets/96838030/e02252f2-7d01-47ef-b0e8-e837a1edacc5)

- For the desktop version everything is fine, you just need to add the SOURCE_CODE (your project github link) here beside your project deployed link.

2024-08-08 06:24 UTC, merged